### ISSUE TITLE
Still under development?

### ISSUE THREAD

**Issue by simonkulessa** [Sighmir/altvRP#1]
Hi, 
I just wanted to ask, if this project is still being developed? :)
Best
Simon

**Comment by guicaulada** [comment]
Hi Simon,

Thank you for your interest in this project.

Due to a recent job change I had to put a break on my side projects, but I plan on continuing this in the future once I have more free time, this hopefully won't take too long, it's just an adapting period on the new job before I can organize my life again to find more free time.

Feel free to contribute to the repository in any way and let me know if I can help with anything.
